### ISSUE TITLE
Cannot build under Mac

### ISSUE THREAD

**Issue by lingnand** [rnons/jinkell#1]
Tried building under Mac using haskell-platform but failed.
Seems that the base version required is 4.7 but I only have 4.6.

Any way around this?

**Comment by rnons** [comment]
Sorry for the inconvenience, I don't own a Mac to test.  

As you can find in the _jinglib.cabal_ and _jinkell.cabal_, the required version of base is `>=4.6`. You said your base version is 4.6, so there shouldn't be a problem.

Can you show me the stdout of `cabal configure`?

Alternatively, you can try relaxing some version constraints in the .cabal files.

**Comment by rnons** [comment]
With commit e79c018, hopefully it works now.

**Comment by lingnand** [comment]
Sorry in fact my version is 4.5 and thus the problem. I've already tried changing `>=4.6` to `>=4.5` but that didn't seem to help.

When I tried to build it I got the following

```
➜  jinglib  cabal install
Resolving dependencies...
In order, the following would be installed:
bytestring-0.10.0.2 (new version)
containers-0.5.2.1 (new version)
dlist-0.5 (new package)
template-haskell-2.8.0.0 (new version)
text-0.11.2.3 (reinstall) changes: bytestring-0.9.2.1 -> 0.10.0.2
attoparsec-0.10.4.0 (new package)
blaze-builder-0.3.1.0 (new package)
hashable-1.2.0.5 (new package)
parsec-3.1.3 (reinstall) changes: bytestring-0.9.2.1 -> 0.10.0.2
unix-2.6.0.1 (new version)
network-2.4.1.2 (new version)
HTTP-4000.2.8 (new version)
unordered-containers-0.2.3.0 (new package)
aeson-0.6.1.0 (new package)
jinglib-2013.3.16 (new package)
cabal: The following packages are likely to be broken by the reinstalls:
network-2.3.1.0
haskell-platform-2012.4.0.0
cgi-3001.1.7.4
HTTP-4000.2.5
Use --force-reinstalls if you want to install anyway.
```

Then if I proceed using `force-reinstalls` I get broken components and the build couldn't finish.

Here's my output of `cabal configure`

```
➜  jinglib  cabal configure
Resolving dependencies...
Configuring jinglib-2013.3.16...
cabal: At least the following dependencies are missing:
aeson >=0.6, bytestring >=0.10, containers >=0.5, network >=2.4
```

**Comment by lingnand** [comment]
Just tried out the new commit, it worked out brilliantly, thanks!

A new problem (albeit silly): how can I start the program once I've built it successfully?

**Comment by lingnand** [comment]
Figured out myself. Thanks!

**Comment by rnons** [comment]
Glad to hear it works.

Jinkell is still a work in progress, much can be improved. If you have any questions or suggestions, feel free to let me know.
