### ISSUE TITLE
problem with encoding (maybe)?

### ISSUE THREAD

**Issue by lingnand** [rnons/jinkell#2]
Just found a new problem; I'm not sure whether this is platform specific but it doesn't appear in your other Haskell app on douban.

Basically I couldn't get any songs for Chinese search phrases. E.g. 许巍 But it works fine for English search phrases e.g. S.H.E.

I haven't had time to look into the code yet. I'm running on a Unicode-compatible terminal emulator called iTerm.

BTW, are there any commands for 'like'ing a song? The only few commands I tried that worked are 'pause' and 'next'

**Comment by rnons** [comment]
Actually, the Chinese query string problem is a known issue, and I haven't figured out how to work around it. If you are interested, you can test in ghci like this.

``` haskell
cd jinglib
ghci
λ> :l Jing/FM.hs
λ> tok <- createSession email pwd
λ> getPlaylist (fromJust tok) "SHE"
λ> getPlaylist (fromJust tok) "许巍"
λ> :m +Codec.Binary.UTF8.String 
λ> getPlaylist (fromJust tok) (encodeString "许巍")
```

It seems to be related to jing.fm api. Or maybe I'm missing something.

p.s. The other commands are `love` and `hate`. A `help` command is to come.

**Comment by lingnand** [comment]
That's interesting. I'll take a look at some other Jing apps and see if there might be some way around it. Thanks for your prompt reply

**Comment by rnons** [comment]
With commit aaa8e0f276, this issue has been resolved, finally.
