### ISSUE TITLE
Typing another search phrase breaks the player..

### ISSUE THREAD

**Issue by lingnand** [rnons/jinkell#3]
I realize that there seem to be some problems with the player after the update. Since then I've changed my system to Arch Linux so I'm not sure whether that might contribute to the issue (although I guess shouldn't?)

It works fine as long as I've only typed in the search phrase once. If I happen to input the second phrase (in the earlier version it would shuffle between the two channels) then it starts to keep switching songs non-stoppedly, and there's no way out of it unless I stop the whole program all together..

Are you aware of this issue or it is only in my case?

**Comment by rnons** [comment]
I'm aware that the second phrase will result in shuffle between two channels. However, I am unable to reproduce your problem. Does it happen every time?

I'm running on Arch as well.

**Comment by lingnand** [comment]
Yes, it does happen every time.
Some features are broken as well, interestingly. For example ':p' will
pause the music but typing it again will not resume the music.

I got 'cabal-install' from the official package repo; after that just
followed the install instruction here.

**Comment by rnons** [comment]
Tha't strange. What is your _mplayer_ and _cabal-install_ version? Mine are

```
# pacman -Qi mplayer
Name           : mplayer
Version        : 35920-1
# pacman -Qi cabal-install
Name           : cabal-install
Version        : 1.16.0.2-2
```

How about make a clean install of jinkell

```
ghc-pkg unregister jinglib
ghc-pkg unregister jinkell
git clone git://github.com/rnons/jinkell.git
cd jinkell/jinglib && cabal install
cd ../jinkell && cabal install
```

**Comment by lingnand** [comment]
Oh I used mplayer2. That might be the culprit.
My cabal-install has the exact same version as yours.

**Comment by rnons** [comment]
Does it work now?

FYI, I'm going to use mpd as music playing backend, because mplayer costs too much memory for such a small application.

Stay tuned. :-)

**Comment by lingnand** [comment]
Yes, it works correctly now. Thanks for your help.

It's a pity that I couldn't understand much Haskell. Otherwise I'd much
like to take a dig into the code and see what I can do as well.

**Comment by rnons** [comment]
Have you ever read [The Cathedral and the Bazaar](http://www.catb.org/~esr/writings/cathedral-bazaar/cathedral-bazaar/)? 

> Every good work of software starts by scratching a developer's personal itch.

Stay curious, keep learning, you will make contribution to open source software in one way or another.
