### ISSUE TITLE
Jinkpd: songs sometimes replay..

### ISSUE THREAD

**Issue by lingnand** [rnons/jinkell#4]
I just tried out Jinkpd and noticed a small bug: when changing to the next song the previous song sometimes replays itself before the next song loads up and takes over.

**Comment by rnons** [comment]
You are right. And sometimes, the first seconds of a song will be replayed as a result of no buffer.

As jinkpd do the music streaming by itself, while jinkell leave it to mplayer. The implementation of jinkpd is a bit more complicated than jinkell. I need more time to learn more about it, maybe new approaches need to be taken.

**Comment by rnons** [comment]
A slight change to the position of `threadDelay` seems to fix it. 

With commit 8f502a6a7a, **jinkpd** is renamed to **jpd**, and there are two executables now: jpd/jpdi

Please help me test it.

**Comment by lingnand** [comment]
我现在总是显示Maybe.fromJust:Nothing
不知道为什么。。是我的library出错了么？但是我已經重新装过一遍cabal了。。

**Comment by rnons** [comment]
把 jinkell.cfg 文件删掉试试。 _~/.jinkell.cfg_ 或 _~/jinkell/jinkell.cfg_。 那个token是会过期的

**Comment by lingnand** [comment]
刚试了下 切歌的时候前首歌不会replay了 但是后首歌的前部分还是有重播的现象。不过比之前已经好很多了

**Comment by rnons** [comment]
后首歌前半部分会重播和网速有关哦，那个`threadDelay`现在设置成了3秒，你可以设成5秒试试。

**Comment by lingnand** [comment]
我这边网络可能不是很好 所以一直会replay; 暂时用回jinkell了

**Comment by rnons** [comment]
You may be interested in my new project [lord](https://github.com/rnons/lord), the previous jpd has been merged into lord. I will provide an option to choose between High-Definition and Low-Definition audio, so that lord can work well in poor network situation.

Close this for now. Anything I can help, don't hesitate to let me know.
